# ref: https://github.com/easimon/maximize-build-space/blob/master/action.yml

name: "Maximize build disk space"

inputs:
  remove-dotnet:
    description: "Removes .NET runtime and libraries. (frees ~17 GB)"
    required: false
    default: "true"
  remove-android:
    description: "Removes Android SDKs and Tools. (frees ~11 GB)"
    required: false
    default: "true"
  remove-haskell:
    description: "Removes GHC (Haskell) artifacts. (frees ~2.7 GB)"
    required: false
    default: "true"
  remove-codeql:
    description: "Removes CodeQL Action Bundles. (frees ~5.4 GB)"
    required: false
    default: "true"
  remove-docker-images:
    description: "Removes cached Docker images. (frees ~3 GB)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      id: report_before
      shell: bash
      run: |
        echo "Memory and swap:"
        free
        echo
        swapon --show
        echo

        echo "Available storage:"
        df -h
        echo

    - name: Maximize build disk space
      id: maximize_space
      shell: bash
      run: |
        set -euo pipefail

        echo -n "  Removing:     "
        if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
          echo -n "dotnet "
        fi
        if [[ ${{ inputs.remove-android }} == 'true' ]]; then
          echo -n "android "
        fi
        if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
          echo -n "haskell "
        fi
        if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
          echo -n "codeql "
        fi
        if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
          echo -n "docker "
        fi
        echo

        echo "Removing unwanted software... "
        if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
          sudo rm -rf /usr/share/dotnet
        fi
        if [[ ${{ inputs.remove-android }} == 'true' ]]; then
          sudo rm -rf /usr/local/lib/android
        fi
        if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
          sudo rm -rf /opt/ghc
        fi
        if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
          sudo rm -rf /opt/hostedtoolcache/CodeQL
        fi
        if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
          sudo docker image prune --all --force
        fi
        sudo apt-get clean
        echo "... done"

    - name: Disk space report after modification
      id: report_after
      shell: bash
      run: |
        echo "Memory and swap:"
        free
        echo
        swapon --show
        echo
        echo "Available storage:"
        df -h
