name: Upload Pages Artifact

inputs:
  path:
    description: "Path of the directory containing the static assets"
    required: true

outputs:
  artifact_id:
    description: "The ID of the artifact that was uploaded."
    value: ${{ steps.upload_pages_artifact.outputs.artifact_id }}

runs:
  using: "composite"
  steps:
    - name: Upload Pages Artifact
      id: upload_pages_artifact
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: ${{ inputs.path }}
